### ISSUE TITLE
Deleted recordings

### ISSUE THREAD

**Issue by Millesimus** [ichdasich/bbb-privacy#1]
Apparently, recordings deleted through Greenlight are not really deleted; at least not immediately. They appear to be stored in "/var/bigbluebutton/deleted". Can you confirm this?

**Comment by ichdasich** [comment]
With scalelite, the recordings are not retained after being deleted. I do not have a non scalelite host for testing (which in my case comes with some extra settings that prevent local recordings to be created). Do you have an environment to test this in? Otherwise, I will have to quickly setup a testsystem tonight.

**Comment by Millesimus** [comment]
I stumbled upon this when adapting my instance (basically just a bbb-install.sh) according to your documentation and I could just recreate it: I make a recording, wait until it is processed, then delete it via Greenlight web interface and find it again in /var/bigbluebutton/deleted/ or rather in its "presentation" subfolder to be precise. It included all xml, json, etc. as well as my cam video.

I could not find any cleanup procedure in the cron, thus I'm not sure whether it would be deleted after a certain period of time or not.

**Comment by ichdasich** [comment]
I will setup a testbox tonight and take a look at whether this has to be a BBB or GL bug.

**Comment by ichdasich** [comment]
Ok, verified in code. deleteRecording (ll 548-570) in bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java does not actually delete recordings but moves it to a deleted directory, so this is definately not a setp issue. ;-)

I will file a bug against bbb, and cc' you in there.

**Comment by ichdasich** [comment]
Created a ticket for BBB; Should be a relatively easy fix for them. Also added documentation and a hotfix (run a cron every 5m cleaning that dir) in https://github.com/ichdasich/bbb-privacy/commit/136c2bf4f103889a03627ff401f7eca73e6c9ad1

**Comment by Millesimus** [comment]
Cool, thank you!
